# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('photoUrl', models.URLField()),
                ('category', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MenuElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url_link', models.URLField()),
                ('level', models.IntegerField()),
                ('parent_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWebsite.MenuElement')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_photoURL', models.URLField(max_length=512)),
                ('opinion', models.TextField()),
            ],
        ),
    ]
