# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWebsite', '0002_auto_20171015_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuelement',
            name='parent_element',
        ),
        migrations.RemoveField(
            model_name='menuelement',
            name='url_link',
        ),
    ]
