# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWebsite', '0004_auto_20171027_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuelement',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
