# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWebsite', '0005_menuelement_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_preview',
            field=models.TextField(default='Put your preview text here'),
        ),
    ]
