# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWebsite', '0006_article_text_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuelement',
            name='url_link',
            field=models.CharField(default='Url here', max_length=256),
        ),
    ]
